### ISSUE TITLE
proxies do not handle POST correctly when HSR is enabled

### ISSUE THREAD

**Issue by werelax** [zab/butler#2]
It just hangs the request there because it is unable to read the payload. I think this is because the `hsr` handling use `body-parser`, and `body-parser` and `http-proxy` have some issues working together. There are some discussions about this on the `http-proxy` repo, for example this [#180](https://github.com/nodejitsu/node-http-proxy/issues/180).

A very simple way to fix this would be to just load `proxiesMiddleware` before `enableHsr` in the middleware stack.

**Comment by jsonmaur** [comment]
Hey sorry for the delay! I'll go ahead and merge/release your fix. Thanks for taking the time to open a PR :)

**Comment by jsonmaur** [comment]
Published via `0.4.2` 👍
